.TH "C:/Users/Sajjad/Documents/Arduino/IntEnseChoI/IntEnseChoIR8/code/master/images.h" 3 "Mon Aug 5 2019" "IntEnseChoI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Sajjad/Documents/Arduino/IntEnseChoI/IntEnseChoIR8/code/master/images.h \- logos and icons  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char PROGMEM \fBdown\fP []"
.br
.RI "Down Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBfdown\fP []"
.br
.RI "Down Filled Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBfleft\fP []"
.br
.RI "Left Filled Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBfright\fP []"
.br
.RI "Right Filled Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBfup\fP []"
.br
.RI "Up Filled Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBleft\fP []"
.br
.RI "Left Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBright\fP []"
.br
.RI "Right Icon\&. "
.ti -1c
.RI "const unsigned char PROGMEM \fBup\fP []"
.br
.RI "UP Icon\&. "
.ti -1c
.RI "const uint8_t PROGMEM \fBteco\fP []"
.br
.RI "TECO Icon\&. "
.ti -1c
.RI "const uint8_t PROGMEM \fBswc\fP []"
.br
.RI "SWC Icon\&. "
.ti -1c
.RI "const uint8_t PROGMEM \fBkit\fP []"
.br
.RI "KIT Icon\&. "
.in -1c
.SH "Detailed Description"
.PP 
logos and icons 

This is the files that contains the logos and icons binary arrays\&.
.PP
\fBAuthor:\fP
.RS 4
Sajjad Hussain
.RE
.PP
\fBDate:\fP
.RS 4
02\&.08\&.2019 
.RE
.PP

.PP
Definition in file \fBimages\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const unsigned char PROGMEM down[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0x9f, 0x90, 0xcf, 0x30, 0xe6, 0x70, 0xf0, 0xf0, 0xf9, 0xf0, 0x9f, 0x90, 0xcf, 0x30, 
  0xe6, 0x70, 0xf0, 0xf0, 0xf9, 0xf0, 0xff, 0xf0
}
.fi
.PP
Down Icon\&. 
.PP
Definition at line 216 of file images\&.h\&.
.SS "const unsigned char PROGMEM fdown[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xe0, 0x70, 0xcf, 0xb0, 0x89, 0x10, 0xb0, 0xd0, 0xb9, 0xd0, 0x9f, 0x90, 0x8f, 0x10, 
  0x86, 0x50, 0xc0, 0xb0, 0xe0, 0x70, 0xff, 0xf0
}
.fi
.PP
Down Filled Icon\&. 
.PP
Definition at line 222 of file images\&.h\&.
.SS "const unsigned char PROGMEM fleft[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xe0, 0x70, 0xc3, 0x30, 0x87, 0x50, 0x8e, 0x90, 0x9c, 0x50, 0x9c, 0x50, 0x8e, 0x90, 
  0x87, 0x10, 0xc3, 0x30, 0xe0, 0x70, 0xff, 0xf0
}
.fi
.PP
Left Filled Icon\&. 
.PP
Definition at line 228 of file images\&.h\&.
.SS "const unsigned char PROGMEM fright[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xe0, 0x70, 0xcc, 0xb0, 0xae, 0x50, 0x97, 0x10, 0xa3, 0x90, 0xa3, 0x90, 0x97, 0x10, 
  0xae, 0x50, 0xcc, 0xb0, 0xe0, 0x70, 0xff, 0xf0
}
.fi
.PP
Right Filled Icon\&. 
.PP
Definition at line 234 of file images\&.h\&.
.SS "const unsigned char PROGMEM fup[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xe0, 0x70, 0xc0, 0xb0, 0x86, 0x50, 0x8f, 0x10, 0x9f, 0x90, 0xb9, 0xd0, 0xb0, 0xd0, 
  0x89, 0x10, 0xcf, 0xb0, 0xe0, 0x70, 0xff, 0xf0
}
.fi
.PP
Up Filled Icon\&. 
.PP
Definition at line 240 of file images\&.h\&.
.SS "const unsigned char PROGMEM left[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xfb, 0xd0, 0xf3, 0x90, 0xe7, 0x30, 0xce, 0x70, 0x9c, 0xf0, 0x9c, 0xf0, 0xce, 0x70, 
  0xe7, 0x30, 0xf3, 0x90, 0xfb, 0xd0, 0xff, 0xf0
}
.fi
.PP
Left Icon\&. 
.PP
Definition at line 246 of file images\&.h\&.
.SS "const unsigned char PROGMEM right[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xbd, 0xf0, 0x9c, 0xf0, 0xce, 0x70, 0xe7, 0x30, 0xf3, 0x90, 0xf3, 0x90, 0xe7, 0x30, 
  0xce, 0x70, 0x9c, 0xf0, 0xbd, 0xf0, 0xff, 0xf0
}
.fi
.PP
Right Icon\&. 
.PP
Definition at line 252 of file images\&.h\&.
.SS "const unsigned char PROGMEM up[]"
\fBInitial value:\fP
.PP
.nf
= {
  0xff, 0xf0, 0xf9, 0xf0, 0xf0, 0xf0, 0xe6, 0x70, 0xcf, 0x30, 0x9f, 0x90, 0xf9, 0xf0, 0xf0, 0xf0, 
  0xe6, 0x70, 0xcf, 0x30, 0x9f, 0x90, 0xff, 0xf0
}
.fi
.PP
UP Icon\&. 
.PP
Definition at line 258 of file images\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IntEnseChoI from the source code\&.
