.TH "E:/Personal/Backup/BackupPhD/PhD/TECO/2019/IntEnseChoI_Controller/Code/IntEnseChoIR9/code/master/mainpage.h" 3 "Thu Aug 22 2019" "IntEnseChoI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Personal/Backup/BackupPhD/PhD/TECO/2019/IntEnseChoI_Controller/Code/IntEnseChoIR9/code/master/mainpage.h \- main page readme file  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
main page readme file 


.PP
Definition in file \fBmainpage\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IntEnseChoI from the source code\&.
