.TH "C:/Users/Sajjad/Documents/Arduino/IntEnseChoI/IntEnseChoIR8/code/master/mainpage.h" 3 "Mon Aug 5 2019" "IntEnseChoI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Sajjad/Documents/Arduino/IntEnseChoI/IntEnseChoIR8/code/master/mainpage.h \- main page readme file  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
main page readme file 


.PP
Definition in file \fBmainpage\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IntEnseChoI from the source code\&.
