.TH "E:/Personal/Backup/BackupPhD/PhD/TECO/2019/IntEnseChoI_Controller/Code/IntEnseChoIR9/code/master/master.ino" 3 "Thu Aug 22 2019" "IntEnseChoI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Personal/Backup/BackupPhD/PhD/TECO/2019/IntEnseChoI_Controller/Code/IntEnseChoIR9/code/master/master.ino \- arduino master file  

.SH SYNOPSIS
.br
.PP
\fC#include 'userdefined\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.RI "initialization of Master "
.ti -1c
.RI "void \fBreadMic\fP ()"
.br
.RI "reading the Microphone with timer function "
.ti -1c
.RI "void \fBloop\fP ()"
.br
.RI "Main loop of Master\&. "
.in -1c
.SH "Detailed Description"
.PP 
arduino master file 

This is the file for master ESP8266 controller, which handles the request/data from
.IP "\(bu" 2
Wifi
.IP "\(bu" 2
push buttons (3)
.IP "\(bu" 2
Joystick
.IP "\(bu" 2
Accelerometer and perform output actions to:
.IP "\(bu" 2
OLED display
.IP "\(bu" 2
Vibration Motor
.IP "\(bu" 2
RGB LED
.IP "\(bu" 2
Buzzer
.PP
.PP
\fBAuthor:\fP
.RS 4
Sajjad Hussain
.RE
.PP
\fBDate:\fP
.RS 4
02\&.08\&.2019 
.RE
.PP

.PP
Definition in file \fBmaster\&.ino\fP\&.
.SH "Function Documentation"
.PP 
.SS "void loop ()"

.PP
Main loop of Master\&. 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP
=buzzerMode)
.PP
=vibrationMode) 
.PP
Definition at line 111 of file master\&.ino\&.
.SS "void readMic (void)"

.PP
reading the Microphone with timer function 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 96 of file master\&.ino\&.
.SS "void setup ()"

.PP
initialization of Master 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 30 of file master\&.ino\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IntEnseChoI from the source code\&.
